### ISSUE TITLE
htmlSafe import is causing error in production build

### ISSUE THREAD

**Issue by lozjackson** [minutebase/ember-inline-svg#105]
I'm getting the following error in our app when building for production since upgrading to ember 3.27

> Uncaught (in promise) TypeError: (0 , t.htmlSafe) is not a function

This line https://github.com/minutebase/ember-inline-svg/blob/master/addon/helpers/inline-svg.js#L1 should be changed to import from `@ember/template` instead of `@ember/string`

**Comment by lozjackson** [comment]
@rlivsey I've created a PR for this

**Comment by raido** [comment]
v1.0.1 published on npm :)
