### ISSUE TITLE
Defaulting not working

### ISSUE THREAD

**Issue by ksnyde** [minutebase/ember-inline-svg#12]
Hey Richard,

Like the plugin and have it working but only after manually configuring the Brocfile:

	var app = new EmberApp({
		svg: {
		    paths: [
		      'public/images'
		    ]
		  }
	});

which based on your instructions should be default behaviour but when I used that I was getting an error that it couldn't locate the SVG.

**Comment by buschtoens** [comment]
Oh sorry. That's fault. I updated a lot of stuff and changed the default path to just `public`.

I forgot to update the docs. Will do so. 

#2 for reference.
