### ISSUE TITLE
Watch out for fat fonts

### ISSUE THREAD

**Issue by jgwhite** [minutebase/ember-inline-svg#14]
This isn’t an issue per se. More a cautionary tale for other users.

Our app was spending around ~500ms in `Flatiron` during incremental builds. Turns out this was due to several large SVG fonts in `public/fonts`.

Simple fix: configure ember-inline-svg just to target `public/images`.

Thanks for the awesome addon :grin:

**Comment by buschtoens** [comment]
Thanks for letting us know! I'll add a note to the docs.

Did your directory strucutre look like (a) or (b) ?

```
// (a)
public/fonts
|- Helvetica
|  |- a.svg        (1 kb)
|  |- b.svg        (1 kb)
|  |- c.svg        (1 kb)
|  ...
|- Comic Sans
|  |- a.svg        (1 kb)
|  |- b.svg        (1 kb)
|  |- c.svg        (1 kb)
|  |-  ...
|- ...


// (b)
public/fonts
|- Helvetica.svg   (500 kb)
|- Comic Sans.svg  (500 kb)
|-  ...
```

How many fonts do you have in there? How big are the individual files?

Maybe I can configure this plugin to show `ember-inline-svg` instead of `Flatiron.`

**Comment by jgwhite** [comment]
@buschtoens more like (b). 4 files around 400–500K apiece.

**Comment by buschtoens** [comment]
I assume you have the optimization enabled. Just for kicks, does [`optimize: false`](https://github.com/minutebase/ember-inline-svg#optimizing) speed up the build?

**Comment by jgwhite** [comment]
`optimize: false` completely removes the delay.

Is caching on the roadmap? It seems like we pay the optimization price even if an unrelated part of the app tree changes.

**Comment by buschtoens** [comment]
Yeah, I was afraid of that happening. :D

*In theory* we already cache unchanged resources. I will definitely look into this problem.  
For now, I'll add a troubleshooting guide to the docs and track the caching in a new issue. :)

**Comment by jgwhite** [comment]
Awesome. Thanks!
