### ISSUE TITLE
A helper named 'inline-svg' could not be found

### ISSUE THREAD

**Issue by NilsDannemann** [minutebase/ember-inline-svg#24]
I've placed the helper like so:
`{{inline-svg "assets/images/loader.svg"}}`

Double checked the path.

Unfortunately I get:
`Uncaught Error: Assertion Failed: A helper named 'inline-svg' could not be found`

Is there something I'm missing?

**Comment by rlivsey** [comment]
Hmm that's odd. 
What version of Ember etc?
Have you restarted the server after installing the addon?

**Comment by NilsDannemann** [comment]
Sorry, my mistake.
Everything works now :-)

**Comment by ValentinTrinque** [comment]
What was the problem then ?

**Comment by cemremengu** [comment]
He probably did not restart the server.. just like me :smile:
