### ISSUE TITLE
Trim `.svg` off the path in Handlebars helper

### ISSUE THREAD

**Issue by buschtoens** [minutebase/ember-inline-svg#4]
`ember-inline-svg` expects the following format:

```hbs
{{inline-svg "/path/to/my/image"}}
```

Out of habit, many people will write the following Handlebars code, which will cause an error:

```hbs
{{inline-svg "/path/to/my/image.svg"}}
```

`ember-inline-svg` should chop off the `.svg` suffix, if present.

**Comment by alekspetrov** [comment]
Ouh, @buschtoens make make my day happy.

**Comment by buschtoens** [comment]
@alekspetrov Oh gosh, sorry. Completely forgot about it. I'll do it.

**Comment by buschtoens** [comment]
I'm on it, but it could take a while, since I'm stuck on Windows 8.1 and about nothing works...

Why doesn't Windows has a Bash already :sob:
