### ISSUE TITLE
Why is viewBox property removed from svg file?

### ISSUE THREAD

**Issue by nhemanth007** [minutebase/ember-inline-svg#65]
`viewBox` property which is present on original svg file is being removed on usage with `inline-svg` helper. This started happening after we upgraded from `0.1.12` to `0.2.1`.

**Comment by raido** [comment]
It is removed because `removeViewBox` plugin is enabled by default in svgo: https://github.com/svg/svgo/blob/master/.svgo.yml#L39

To disable the behaviour add it to config like this: https://github.com/minutebase/ember-inline-svg#optimizing
